config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  root 'keywords#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :tweets

  def grab_tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
      config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
      config.access_token_secret = ENV["TWITTER_ACCESS_TOKEN_SECRET"]
    end

    client.search(self.word, :result_type => "recent").take(100).collect do |tweet|
      new_tweet = Tweet.new
      
      new_tweet.tweet_id          = tweet.id.to_s
      new_tweet.tweet_created_at  = tweet.created_at 
      new_tweet.text              = tweet.text
      new_tweet.user_uid          = tweet.user.id
      new_tweet.user_name         = tweet.user.name
      new_tweet.user_screen_name  = tweet.user.screen_name
      new_tweet.user_image_url    = tweet.user.profile_image_url.to_s
      new_tweet.keyword           = self

      new_tweet.save
    end
  end

  def self.grab_all_tweets
    Keyword.all.each do |keyword|
      keyword.grab_tweets
    end
    expire_fragment('keywords_home_table')
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :keyword, touch: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @tweets=@keyword.tweets.order("created_at DESC").page(params[:page]).per_page(50)

    #@keyword.grab_tweets
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        @keyword.grab_tweets
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_with(model: keyword, local: true) do |form| %>
  <% if keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word, id: :keyword_word %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h2>Editing Keyword</h2>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Keywords</h2>

<% cache('keywords_home_table', skip_digest: true) do %>
  <table>
    <thead>
      <tr>
        <th>Word</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <% @keywords.each do |keyword| %>
        <tr>
          <td><%= keyword.word %></td>
          <td><%= keyword.tweets.count %>
          <td><%= link_to 'Show', keyword %></td>
          <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
          <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h2>New Keyword</h2>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @keyword.word %>
</p>

<% cache "keyword_show_id#{@keyword.id}_p#{params[:page]}", skip_digest: true, expires_in: 5.minutes do %>
  <h2>Latest Tweets  (<%= @keyword.tweets.count %>)</h2>
  <ul>
    <% @tweets.each do |twitt| %>
      <li><img src="<%= twitt.user_image_url %>" width="30"> <%= twitt.user_screen_name %> <%= twitt.text %>  %></li>
    <% end %>
  </ul>
  <%= will_paginate @tweets %>
<% end %>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetscope</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Tweetscope - v1</h1>
    <hr/>
    
    <%= yield %>

    <hr/>
    <div style="text-align:center">Tweetscope for Heroku Course </div>
  </body>
</html>